spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:15432/pagamento
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
server:
  compression:
    enabled: 'true'
  port: 8003
  forward-headers-strategy: native