spring:
  application:
    name: ecommerce-login-service
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
server:
  compression:
    enabled: 'true'
  port: 8002
  forward-headers-strategy: native
rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem
logging:
  level:
    org.springframework.security: trace