spring:
  application:
    name: ecommerce-login-service
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:15432/login
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
server:
  compression:
    enabled: 'true'
  port: 8002
  forward-headers-strategy: native
rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem
logging:
  level:
    org.springframework.security: trace